[build]
  # No build command needed for static HTML
  publish = "."
  functions = "netlify/functions"

[build.environment]
  # Set any environment variables if needed
  # NODE_VERSION = "18"

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  # Handle 404s gracefully
  from = "/*"
  to = "/index.html"
  status = 200

# Function configuration
[functions]
  node_bundler = "esbuild"
  included_files = ["node_modules/**"]

# Function-specific settings
[functions."proxy"]
  timeout = 30 